### ISSUE TITLE
Добавление и обновление студента

### ISSUE THREAD

**Issue by nikitusik** [nikitusik/spring-boot-netcracker#1]
Необходимо реализовать фронт на добавление и обновление студента. Файлы лежат в ресурсах

**Comment by vladmirkulov13** [comment]
чутка фронт поделал, добавил header footer, в отдельные файлы их вынес, чтобы проще было вставлять в html файлы остальные, студента пока не трогал, сейчас поразбираюсь еще немного

**Comment by nikitusik** [comment]
да увидел, теперь выглядит поинтересней))
жду от тебя студентов
