### ISSUE TITLE
Поиск студентов по группе

### ISSUE THREAD

**Issue by nikitusik** [nikitusik/spring-boot-netcracker#2]
Я допилил бэк для поиска студентов по группе. Надо только на форме list-students прикрутить кнопку для поиска. Сейчас поиск работает, если в адрес браузера вбить ссылку напрямую http://localhost:8080/students/search/номер.  Я накидал на list-students поле для ввода и ссылку, но они не рабочие если что. Вот если их как-нибудь связать это прям будет супер, но я чет не смог) Ну или как нибудь по другому решить эту проблему...

**Comment by vladmirkulov13** [comment]
У нас короче в чем прикол, гиперссылка, по которой переходит пользователь после нажатия на search - она постоянная и {number} не меняется никогда. В кодировке выглядит так: http://localhost:8080/students/search/%7Bnumber%7D. Вот, а работает нормально если вручную URL правильный прописать. Поэтому как я понял ошибка в html файле в том, где гиперссылка на поиск. Исправить я думаю можно с помощью введения кнопки и postmapping в контроллер, который принимает эту кнопку, но я не уверен и реализовать не получилось у меня.

**Comment by nikitusik** [comment]
Да ты прав, видимо нельзя динамически поменять ссылку, у меня тоже не получилось это реализовать в html. Я в итоге реализовал через дополнительную форму все это дело и обернул контролером, вроде работает
